// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function AddScanDir(arg1:string):Promise<void>;

export function ClearDoubanInfo(arg1:number):Promise<void>;

export function ClearMisrecords():Promise<void>;

export function CreateNote(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<number>;

export function CreateTag(arg1:string,arg2:string):Promise<number>;

export function DataDir():Promise<string>;

export function DeleteBook(arg1:number):Promise<void>;

export function DeleteNote(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function DoubanSearch(arg1:string):Promise<Array<models.DoubanBook>>;

export function EnrichAllMissing():Promise<number>;

export function EnrichBookByTitle(arg1:number,arg2:models.DoubanBook):Promise<void>;

export function FetchDouban(arg1:number):Promise<models.Book>;

export function GetBook(arg1:number):Promise<models.Book>;

export function GetBookData(arg1:number):Promise<string>;

export function GetBookDataRange(arg1:number,arg2:number,arg3:number):Promise<string>;

export function GetBooks(arg1:main.BookQueryInput):Promise<Array<models.Book>>;

export function GetCoverData(arg1:number):Promise<string>;

export function GetMisrecords():Promise<Array<models.Misrecord>>;

export function GetSettings():Promise<models.Settings>;

export function GetStats():Promise<models.Stats>;

export function GetSystemDarkMode():Promise<boolean>;

export function GetVersion():Promise<string>;

export function ListNotes(arg1:number):Promise<Array<models.Note>>;

export function ListReadingSessions(arg1:number):Promise<Array<models.ReadingSession>>;

export function ListScanDirs():Promise<Array<string>>;

export function ListTags():Promise<Array<models.Tag>>;

export function MarkMisrecord(arg1:number,arg2:string):Promise<void>;

export function OpenBookFolder(arg1:number):Promise<void>;

export function PickScanDir():Promise<string>;

export function RemoveMisrecord(arg1:number):Promise<void>;

export function RemoveScanDir(arg1:string):Promise<void>;

export function ReportReading(arg1:number,arg2:number,arg3:number):Promise<number>;

export function SaveProgress(arg1:number,arg2:string,arg3:number,arg4:number,arg5:number):Promise<void>;

export function ScanStart(arg1:Array<string>):Promise<void>;

export function ScanStatus():Promise<boolean>;

export function SetBookTags(arg1:number,arg2:Array<number>):Promise<void>;

export function SetSettings(arg1:models.Settings):Promise<void>;

export function SetUiTheme(arg1:string):Promise<void>;

export function UnmarkMisrecord(arg1:number):Promise<void>;

export function UpdateBookMeta(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateNote(arg1:number,arg2:string):Promise<void>;

export function UpdateTag(arg1:number,arg2:string,arg3:string):Promise<void>;
