// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function AddScanDir(arg1:string):Promise<void>;

export function AutoEnrichBook(arg1:number):Promise<models.Book>;

export function ClearDoubanInfo(arg1:number):Promise<void>;

export function ClearMisrecords():Promise<void>;

export function CompressPdf(arg1:models.PdfCompressOptions):Promise<models.PdfCompressResult>;

export function ConvertPdfToEpub(arg1:models.PdfToEpubOptions):Promise<models.PdfToEpubResult>;

export function CreateNote(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<number>;

export function CreateTag(arg1:string,arg2:string):Promise<number>;

export function DataDir():Promise<string>;

export function DeleteBook(arg1:number):Promise<void>;

export function DeleteNote(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function DetectGhostscript():Promise<models.PdfCompressGhostscript>;

export function DoubanRunning():Promise<boolean>;

export function DoubanSearch(arg1:string):Promise<Array<models.DoubanBook>>;

export function EnrichAllMissing():Promise<number>;

export function EnrichBookByTitle(arg1:number,arg2:models.DoubanBook):Promise<void>;

export function EpubInspect(arg1:string):Promise<models.EpubFileInfo>;

export function EpubToPdf(arg1:models.EpubToPdfOptions):Promise<models.EpubToPdfResult>;

export function ExtractPdfPages(arg1:models.PdfExtractOptions):Promise<models.PdfExtractResult>;

export function FetchDouban(arg1:number):Promise<models.Book>;

export function FreezeTag(arg1:number,arg2:boolean):Promise<void>;

export function GetBook(arg1:number):Promise<models.Book>;

export function GetBookData(arg1:number):Promise<string>;

export function GetBookDataRange(arg1:number,arg2:number,arg3:number):Promise<string>;

export function GetBooks(arg1:main.BookQueryInput):Promise<Array<models.Book>>;

export function GetCoverData(arg1:number):Promise<string>;

export function GetMisrecords():Promise<Array<models.Misrecord>>;

export function GetSettings():Promise<models.Settings>;

export function GetStats():Promise<models.Stats>;

export function GetSystemDarkMode():Promise<boolean>;

export function GetVersion():Promise<string>;

export function KKFileAddr():Promise<string>;

export function ListNotes(arg1:number):Promise<Array<models.Note>>;

export function ListReadingSessions(arg1:number):Promise<Array<models.ReadingSession>>;

export function ListScanDirs():Promise<Array<string>>;

export function ListTags():Promise<Array<models.Tag>>;

export function MarkMisrecord(arg1:number,arg2:string):Promise<void>;

export function MergePdfs(arg1:models.PdfMergeOptions):Promise<models.PdfMergeResult>;

export function OpenBookFolder(arg1:number):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenWithKKFileView(arg1:number):Promise<string>;

export function PdfCompressInspect(arg1:string,arg2:string):Promise<models.PdfCompressInfo>;

export function PdfExtractInspect(arg1:string,arg2:string):Promise<models.PdfExtractInfo>;

export function PdfInspect(arg1:string,arg2:string):Promise<models.PdfFileInfo>;

export function PdfMergeInspect(arg1:Array<string>,arg2:Record<string, string>):Promise<Array<models.PdfMergeFile>>;

export function PdfMetaInspect(arg1:string,arg2:string):Promise<models.PdfMetaInfo>;

export function PickEpubFile():Promise<string>;

export function PickGhostscriptExe():Promise<string>;

export function PickOutDir(arg1:string):Promise<string>;

export function PickOutPdfFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function PickPdfFile():Promise<string>;

export function PickPdfFiles():Promise<Array<string>>;

export function PickScanDir():Promise<string>;

export function ReadPdfData(arg1:string):Promise<string>;

export function RemoveMisrecord(arg1:number):Promise<void>;

export function RemovePdfPassword(arg1:models.PdfProtectOptions):Promise<models.PdfFileInfo>;

export function RemoveScanDir(arg1:string):Promise<void>;

export function ReportReading(arg1:number,arg2:number,arg3:number):Promise<number>;

export function SavePdfImage(arg1:models.PdfImageOptions):Promise<models.PdfImageResult>;

export function SavePdfMeta(arg1:models.PdfMetaOptions):Promise<models.PdfMetaResult>;

export function SaveProgress(arg1:number,arg2:string,arg3:number,arg4:number,arg5:number):Promise<void>;

export function ScanStart(arg1:Array<string>):Promise<void>;

export function ScanStatus():Promise<boolean>;

export function SetBookTags(arg1:number,arg2:Array<number>):Promise<void>;

export function SetKKFileAddr(arg1:string):Promise<void>;

export function SetPdfPassword(arg1:models.PdfProtectOptions):Promise<models.PdfFileInfo>;

export function SetSettings(arg1:models.Settings):Promise<void>;

export function SetUiTheme(arg1:string):Promise<void>;

export function StartEnrichAll():Promise<number>;

export function UnmarkMisrecord(arg1:number):Promise<void>;

export function UpdateBookMeta(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateNote(arg1:number,arg2:string):Promise<void>;

export function UpdateTag(arg1:number,arg2:string,arg3:string):Promise<void>;
