// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddScanDir(arg1) {
  return window['go']['main']['App']['AddScanDir'](arg1);
}

export function ClearDoubanInfo(arg1) {
  return window['go']['main']['App']['ClearDoubanInfo'](arg1);
}

export function ClearMisrecords() {
  return window['go']['main']['App']['ClearMisrecords']();
}

export function CreateNote(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTag(arg1, arg2) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2);
}

export function DataDir() {
  return window['go']['main']['App']['DataDir']();
}

export function DeleteBook(arg1) {
  return window['go']['main']['App']['DeleteBook'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DoubanSearch(arg1) {
  return window['go']['main']['App']['DoubanSearch'](arg1);
}

export function EnrichAllMissing() {
  return window['go']['main']['App']['EnrichAllMissing']();
}

export function EnrichBookByTitle(arg1, arg2) {
  return window['go']['main']['App']['EnrichBookByTitle'](arg1, arg2);
}

export function FetchDouban(arg1) {
  return window['go']['main']['App']['FetchDouban'](arg1);
}

export function GetBook(arg1) {
  return window['go']['main']['App']['GetBook'](arg1);
}

export function GetBookData(arg1) {
  return window['go']['main']['App']['GetBookData'](arg1);
}

export function GetBookDataRange(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBookDataRange'](arg1, arg2, arg3);
}

export function GetBooks(arg1) {
  return window['go']['main']['App']['GetBooks'](arg1);
}

export function GetCoverData(arg1) {
  return window['go']['main']['App']['GetCoverData'](arg1);
}

export function GetMisrecords() {
  return window['go']['main']['App']['GetMisrecords']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetSystemDarkMode() {
  return window['go']['main']['App']['GetSystemDarkMode']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ListNotes(arg1) {
  return window['go']['main']['App']['ListNotes'](arg1);
}

export function ListReadingSessions(arg1) {
  return window['go']['main']['App']['ListReadingSessions'](arg1);
}

export function ListScanDirs() {
  return window['go']['main']['App']['ListScanDirs']();
}

export function ListTags() {
  return window['go']['main']['App']['ListTags']();
}

export function MarkMisrecord(arg1, arg2) {
  return window['go']['main']['App']['MarkMisrecord'](arg1, arg2);
}

export function OpenBookFolder(arg1) {
  return window['go']['main']['App']['OpenBookFolder'](arg1);
}

export function PickScanDir() {
  return window['go']['main']['App']['PickScanDir']();
}

export function RemoveMisrecord(arg1) {
  return window['go']['main']['App']['RemoveMisrecord'](arg1);
}

export function RemoveScanDir(arg1) {
  return window['go']['main']['App']['RemoveScanDir'](arg1);
}

export function ReportReading(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReportReading'](arg1, arg2, arg3);
}

export function SaveProgress(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveProgress'](arg1, arg2, arg3, arg4, arg5);
}

export function ScanStart(arg1) {
  return window['go']['main']['App']['ScanStart'](arg1);
}

export function ScanStatus() {
  return window['go']['main']['App']['ScanStatus']();
}

export function SetBookTags(arg1, arg2) {
  return window['go']['main']['App']['SetBookTags'](arg1, arg2);
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}

export function SetUiTheme(arg1) {
  return window['go']['main']['App']['SetUiTheme'](arg1);
}

export function UnmarkMisrecord(arg1) {
  return window['go']['main']['App']['UnmarkMisrecord'](arg1);
}

export function UpdateBookMeta(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateBookMeta'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateNote(arg1, arg2) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2);
}

export function UpdateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2, arg3);
}
